name: Build and Release Arch Image

on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Pacman Dependencies
        id: cache-pacman-deps
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ runner.os }}-cache-pacman-deps-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-cache-pacman-deps-${{ github.ref_name }}
            ${{ runner.os }}-cache-pacman-deps

      # Set up Podman
      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      
      - name: Build Rust project
        run: |
          cd system && cargo build --release && cd -

      # Build the Docker image using Podman
      - name: Build Docker image
        run: |
          podman build -t archbuild:latest .
      
      - name: Build artifact
        env:
          USER: ${{ secrets.USER }}
          PW: ${{ secrets.PW }}
        run: |
          podman run --cap-add SYS_ADMIN --security-opt unmask=/proc/* --security-opt label=disable -v ./cache:/var/cache/pacman/pkg --env USER=$USER --env PW=$PW --name archbuild --replace archbuild
          podman cp archbuild:/arch.sqfs .

          podman rm archbuild

          mkdir dist
          split --bytes=1G -d arch.sqfs dist/chunk-

          sha256sum arch.sqfs dist/chunk-* > dist/sha256sums.txt

          echo "Successfully built artifact"
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
