name: Build and Release Arch Image

on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Podman
      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      # Build the Docker image using Podman
      - name: Build Docker image
        run: |
          podman build -t archbuild:latest .
      
      - name: Build artifact
        run: |
          podman run --privileged --name archbuild archbuild
          podman cp archbuild:/arch.sqfs .

          podman rm archbuild
          mkdir dist
          split --bytes=1G -d arch.sqfs dist/chunk-
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
